### ISSUE TITLE
iphonex适配

### ISSUE THREAD

**Issue by tianfangcx** [tianfangcx/my-h5-skills#3]
### 安全区域
适配的核心目的就是尽量把我们的页面布局放在安全区域
1、使用viewport-fit=cover让我们可以使用constant函数
```css
body {
    padding-top: constant(safe-area-inset-top);   //为导航栏+状态栏的高度 88px            
    padding-left: constant(safe-area-inset-left);   //如果未竖屏时为0                
    padding-right: constant(safe-area-inset-right); //如果未竖屏时为0                
    padding-bottom: constant(safe-area-inset-bottom);//为底下圆弧的高度 34px       
}
```
